trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: java -version
    - bash: mvn -version
    - bash: node --version
    - bash: python --version
    - bash: echo ArtifactStagingDirectory:$(Build.ArtifactStagingDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: echo ArtifactStagingDirectory:$(Build.ArtifactStagingDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)