trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build / FirstJob
    - bash: echo $(PipelineLevelVariable)
    # NEW CONFIG
    - bash: echo BuildNumber:$(Build.BuildNumber)
    - bash: echo BuildId:$(Build.BuildId)
    - bash: echo SourceBranchName:$(Build.SourceBranchName)
    - bash: echo SourcesDirectory:$(Build.SourcesDirectory)
    - bash: echo ArtifactStagingDirectory:$(Build.ArtifactStagingDirectory)
    - bash: echo DefaultWorkingDirectory:$(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)

  # - job: SecondJob
  #   steps:
  #   - bash: echo Build / SecondJob